name: publish
env:
  ProjectName: KeyAsio.Net
on:
  create:
    tags:
      - "v*.*.*"
  
jobs:
  build:
    name: Build and Release
    if: ${{ StartsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: |
        dotnet restore KeyAsio.Gui

    - name: Publish
      if: ${{ success() }}
      run: |
        echo ${{ github.ref }}      
        dotnet publish KeyAsio.Gui --no-restore --framework net6.0-windows --runtime win-x64 --self-contained --configuration Release --output ci-publish-win64
        dotnet publish KeyAsio.Gui --no-restore --framework net6.0-windows --runtime win-x86 --self-contained --configuration Release --output ci-publish-win32
        dotnet publish KeyAsio.Gui --no-restore --framework net6.0-windows --configuration Release --output ci-publish
        
    - name: Get tag
      uses: dawidd6/action-get-tag@v1
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      id: tag
        
    - name: Pack via 7z
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      run: |
        mkdir -p ./ci-pack/
        7z a -mx9 -mfb=273 -ms -md=31 -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 "./ci-pack/${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}.7z" "./ci-publish/*" -x!"${{ env.ProjectName }}" -r
        7z a -mx9 -mfb=273 -ms -md=31 -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 "./ci-pack/${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}-win64.7z" "./ci-publish-win64/*" -x!"${{ env.ProjectName }}" -r
        7z a -mx9 -mfb=273 -ms -md=31 -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 "./ci-pack/${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}-win32.7z" "./ci-publish-win32/*" -x!"${{ env.ProjectName }}" -r
        
    - name: Create a new GitHub release if a new tag is pushed
      uses: softprops/action-gh-release@v1
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      env:
        GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
      with:
        body: |
          [Forum page](https://osu.ppy.sh/community/forums/topics/1602658)

          ## Release notes
          1. Place holder
          
          ### Installation
          .NET 6.0 Desktop Runtime is required for the smallest asset.
          For the other two assets with "-win32" and "-win64" postfix, you don't need to install anything more.
        name: ${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}
        prerelease: true
        draft: false
        files: |
          ./ci-pack/${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}.7z
          ./ci-pack/${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}-win64.7z
          ./ci-pack/${{ env.ProjectName }}-${{ steps.tag.outputs.tag }}-win32.7z